# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: pylmps

steps:

- checkout: self
  submodules: true
  persistCredentials: true

- script: |
    cd lammps
    mkdir build
    cd build
    cmake ../cmake
    cmake -D BUILD_SHARED_LIBS=ON -D PKG_PYTHON=ON -D PKG_REPLICA=ON -D PKG_USER-COLVARS=ON -D PKG_CLASS2=ON -D PKG_KSPACE=ON -D PKG_MANYBODY=ON -D PKG_MC=ON -D PKG_USER-MOFFF=ON -D PKG_USER-H5MD=ON -D PKG_USER-MISC=ON -D PKG_MOLECULE=ON -D  PKG_USER-REAXC=ON ../cmake
    cmake --build . 
  displayName: 'build lammps'

- script: |
    source source_me 
    cd pylmps/tests/generic
    mpirun -np 2 python3 test_opt_hkust1.py
  displayName: 'testing pylmps MOF-FF opt'


