# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: pylmps

steps:

- checkout: self
  submodules: true
  persistCredentials: true

- script: |
    cd lammps
    mkdir build
    cd build
    cmake ../cmake
    cmake -D BUILD_SHARED_LIBS=ON PKG_PYTHON=ON PKG_REPLICA=ON PKG_USER-COLVARS=ON PKG_CLASS2=ON PKG_KSPACE=ON PKG_MANYBODY=ON PKG_MC=ON PKG_USER-MOFFF=ON PKG_USER-H5MD=ON PKG_USER-MISC=ON PKG_MOLECULE=ON  PKG_USER-REAXC=ON ../cmake
    cmake --build . --parallel 4
  displayName: 'build lammps'

- script: |
    source source_me 
    cd pylmps/tests/generic
    mpirun -np 2 python3 test_opt_hkust1.py
  displayName: 'testing pylmps MOF-FF opt'


