#!/usr/bin/env python3
# -*- coding: utf-8 -*-

###########################################################################
#
#  Script to convert (old) BB (former SBU) files into the new format
#
############################################################################

import os
import sys
import molsys

try:
    atom_identifier = sys.argv[2]
except:
    atom_identifier = 'He'



fname = sys.argv[1]
name = fname.rsplit('.',1)[0]

m = molsys.mol.from_file(fname)


m.addon('bb')

m.bb.add_bb_info(conn_identifier=atom_identifier,center_point = 'coc')
m.periodic=False
m.cellparams = None
m.cell = None
m.is_bb   =True 
m.write('bb_%s.mfpx' % (name,))


