#!/usr/bin/env python3
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to align a structure onto its principle axes - mainly intended
#  for visualization purposes
#
#########################################################################


import sys
import string
import molsys.util.unit_cell as unit_cell
import molsys.mol as mol
import molsys.util.rotations as rotations

fi = sys.argv[1]
fi_type = fi.split('.')[-1]

fo,fo_type = fi,fi_type

if len(sys.argv) == 3:
    fo = sys.argv[2]
    fo_type = fo.rsplit('.',1)[-1]

m = mol()
m.read(fi, ftype = fi_type)

### check here whether the structure is a bb already! in this case do not change anything bb related

m.center_com()

m.xyz = rotations.align_pax(m.xyz,masses=m.get_mass())



m.write(fo, ftype = fo_type)
