#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import molsys.mol as mol
import molsys.util.atomtyper as atomtyper
import sys


name = sys.argv[1]

m = mol()
m.read(name)
at = atomtyper(m)
at()

m.write(name)
