#!/usr/bin/env python3
# -*- coding: utf-8 -*-

""" script to extract species in specific frame from DB

"""


from molsys.util import findR

import argparse
import os


#
# Create commandline parser
#
parser = argparse.ArgumentParser()

parser.add_argument('-db',    type=str, nargs=1,   default="analyze"  , help='Path to database')
parser.add_argument('-fmfp5', type=str, nargs=1,   default="reax.mfp5", help='Path to trajectory')
parser.add_argument('-stage', type=str, nargs=1,   default="sample"   , help='Name of stage')  
parser.add_argument('-fids',  type=int, nargs='*', default=[]         , help='list of frame IDs to process')

args = parser.parse_args()
fids = args.fids

db_path   = args.db[0] 
mfp5_path = args.fmfp5[0]
mfp5_path = os.path.abspath(mfp5_path)
stage     = args.stage[0]

#
# Sanity check(s)
#
assert len(fids) > 0, "No frame IDs given"

#
# Create findR and process frames
#
fr = findR.findR(mfp5_path, stage, db_path)

for fid in fids:
   frame = fr.process_frame(fid)
   frame.write_species()


