#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import molsys
import sys
import os

name = sys.argv[1]
if name == "all":
    print ("fragmentizing all mfpx files in the current folder ... beware")
    mollist = [x for x in os.listdir(".") if x.rsplit('.',1)[-1]=='mfpx']
else:
    mollist = [name]

frag = molsys.util.fragmentizer()
for name in mollist:
    m = molsys.mol()
    m.read(name)
    at = molsys.util.atomtyper(m)
    at()
    frag(m, verbose=True)
    m.write(name)

