#!/usr/bin/env python3 
# -*- coding: utf-8 -*-

###########################################################################
#
#   Script to generate a pxrd pattern with Fox from an mfpx file
#
############################################################################

import sys
import os
import numpy
import matplotlib.pyplot as plt


fname = sys.argv[1]
print(sys.argv) 
name = fname.rsplit('.',1)[0]

os.system('x2x2 %s %s.cif' % (fname,name))

os.system('Fox-nogui %s.cif --cif2pattern 1.5406 50 10000 .1 %s.pxrd > pxrd.out' % (name,name))



