#!/usr/bin/env python3
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to set the cellparams of a mfpx file ## old file is gone afterwards
#
#########################################################################


import sys
import string
import molsys.mol as mol


fi = sys.argv[1]
fi_type = fi.split('.')[-1]
m = mol()
m.read(fi, ftype = fi_type)

cellstring = sys.argv[2]
csp = [i for i in cellstring.split() if i != '']
print(cellstring, csp)
cell = [float(i) for i in csp]

if len(cell) == 1:
    # scaling by a factor
    fact = cell[0]
    cp = m.get_cellparams()
    cp[0] *= fact; cp[1] *= fact; cp[2] *= fact # scale the lengths of the vectors
    m.set_cellparams(cp)
elif len(cell) == 3: ## only abc are provided
    print('setting cell abc to:', cell)
    m.set_cellparams(cell+[90.0,90.0,90.0],cell_only=False) 
elif len(cell) == 6: # abc alpha beta gamma are provided
    m.set_cellparams(cell,cell_only=False)
else:
    raise NotImplementedError('setting cell vectors is not yet implemented')

m.write(fi, ftype = fi_type)
