#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
       vmd_md_species

        convert all md_species to thumbnails and upload to RDB

"""

import tempfile
import sys
import os
from molsys.util import RDB
from molsys.util import thumbnail
from molsys.util import print_progress

if len(sys.argv) < 2:
    print("usage:\n\n  opt_vmd_species <db_path>\n")
    exit()

db_path = sys.argv[1]

rdb = RDB.RDB(db_path)
db = rdb.db

replot = False
if len(sys.argv) > 2:
    replot = bool(sys.argv[2]) 
    print("I will replot all graphics")


if replot:
    md_spec_rows = db(db.md_species).select()
else:
    md_spec_rows = db(db.md_species.png == None).select()

nitems = len(md_spec_rows)

with tempfile.TemporaryDirectory() as tmpdir:
    os.chdir(tmpdir)
    for i, mdspec in enumerate(md_spec_rows):
        print_progress.print_progress(i, nitems)
        mol, fname = rdb.get_md_species_mol(mdspec)
        img_fname = fname.rsplit(".", 1)[0] + ".png"
        if mol.get_natoms() < 5:
            size = 100
            scale = 1.0
        else:
            size = 200
            scale = 1.3
        thumbnail.thumbnail(mol, size=size, scale=scale, fname=img_fname, own_bonds=True)
        imgf = open(img_fname, "rb")
        mdspec.png = db.md_species.png.store(imgf, img_fname)
        mdspec.update_record()
    db.commit()


