#! /usr/bin/env python

# -*- coding: utf-8 -*-

###########################################################################
#
#   Script to generate LAMMPS input for UFF                      
#
############################################################################

import sys
import os
import pylmps

fname = sys.argv[1]
name = fname.rsplit('.',1)[0]

assert os.path.isfile(name + ".mfpx")
if os.path.isfile(name + ".ric") and os.path.isfile(name + ".par"):
    # use exisitng FF
    ff = "file"
else:
    ff = "MOF-FF"

pl = pylmps.pylmps(name)

pl.setup(local=True, ff=ff)

pl.MIN(0.1)

pl.LATMIN_boxrel(0.1, 0.1)
pl.LATMIN_sd(0.1, 0.1)
pl.LATMIN_sd(0.05, 0.05)
pl.MIN(0.01)

pl.write(name+'_MOF-FF_latopt.mfpx')




