#!/usr/bin/env python3 

# -*- coding: utf-8 -*-

###########################################################################
#
#   Script to generate LAMMPS input for UFF                      
#
############################################################################

import sys
import os
import pylmps

fname = sys.argv[1]
name = fname.rsplit('.',1)[0]
print('name:', name)


pl = pylmps.pylmps(name)

pl.setup(local=True, ff="UFF",uff='UFF4MOF')

pl.MIN(0.1)

pl.LATMIN_boxrel(0.1, 0.1)
pl.LATMIN(0.1, 0.1)
pl.MIN(0.0001)

pl.write(name+'_UFF4MOF_latopt.mfpx')




